<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AdminMenusSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('admin_menus')->insert([
            [
                'parent_id' => 0,
                'custom_order' => 0,
                'title' => 'dashboard',
                'icon' => 'mdi:chart-line',
                'url' => '/dashboard',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 1,
                'is_full' => 0,
                'extension' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'parent_id' => 0,
                'custom_order' => 0,
                'title' => 'admin_system',
                'icon' => 'material-symbols:settings-outline',
                'url' => '/system',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'is_full' => 0,
                'extension' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'parent_id' => 2,
                'custom_order' => 0,
                'title' => 'admin_users',
                'icon' => 'ph:user-gear',
                'url' => '/system/admin_users',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'is_full' => 0,
                'extension' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'parent_id' => 2,
                'custom_order' => 0,
                'title' => 'admin_roles',
                'icon' => 'carbon:user-role',
                'url' => '/system/admin_roles',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'is_full' => 0,
                'extension' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'parent_id' => 2,
                'custom_order' => 0,
                'title' => 'admin_permission',
                'icon' => 'fluent-mdl2:permissions',
                'url' => '/system/admin_permission',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'is_full' => 0,
                'extension' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'parent_id' => 2,
                'custom_order' => 0,
                'title' => 'admin_menu',
                'icon' => 'ant-design:menu-unfold-outlined',
                'url' => '/system/admin_menu',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'is_full' => 0,
                'extension' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'parent_id' => 2,
                'custom_order' => 0,
                'title' => 'admin_setting',
                'icon' => 'akar-icons:settings-horizontal',
                'url' => '/system/admin_setting',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'is_full' => 0,
                'extension' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'parent_id' => 0,
                'custom_order' => 1,
                'title' => '数据字典',
                'icon' => 'fluent-mdl2:dictionary',
                'url' => '/admin_dict',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'is_full' => 0,
                'extension' => 'slowlyo.owl-dict',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'parent_id' => 0,
                'custom_order' => 2,
                'title' => '系统日志',
                'icon' => 'octicon:log-24',
                'url' => '/owl-log-viewer',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'is_full' => 0,
                'extension' => 'slowlyo.owl-log-viewer',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'parent_id' => 0,
                'custom_order' => 3,
                'title' => 'amis json 解析',
                'icon' => 'mdi:code-json',
                'url' => '/slow-amis-json-parse',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'is_full' => 0,
                'extension' => 'slowlyo.owl-amis-json-parse',
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);
    }
}
