<?php

namespace PHPSTORM_META {
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\AuthController::createButton(), 0, 'dialog', 'drawer', true);
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\AuthController::createButton(), 1, 'xs', 'sm', 'md', 'lg', 'xl', 'full');
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\AuthController::rowEditButton(), 0, 'dialog', 'drawer', true);
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\AuthController::rowEditButton(), 1, 'xs', 'sm', 'md', 'lg', 'xl', 'full');
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\AuthController::rowShowButton(), 0, 'dialog', 'drawer', true);
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\AuthController::rowShowButton(), 1, 'xs', 'sm', 'md', 'lg', 'xl', 'full');
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\AuthController::rowActions(), 0, 'dialog', 'drawer', true);
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\AuthController::rowActions(), 1, 'xs', 'sm', 'md', 'lg', 'xl', 'full');
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\AdminUserController::createButton(), 0, 'dialog', 'drawer', true);
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\AdminUserController::createButton(), 1, 'xs', 'sm', 'md', 'lg', 'xl', 'full');
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\AdminUserController::rowEditButton(), 0, 'dialog', 'drawer', true);
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\AdminUserController::rowEditButton(), 1, 'xs', 'sm', 'md', 'lg', 'xl', 'full');
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\AdminUserController::rowShowButton(), 0, 'dialog', 'drawer', true);
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\AdminUserController::rowShowButton(), 1, 'xs', 'sm', 'md', 'lg', 'xl', 'full');
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\AdminUserController::rowActions(), 0, 'dialog', 'drawer', true);
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\AdminUserController::rowActions(), 1, 'xs', 'sm', 'md', 'lg', 'xl', 'full');
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\AdminMenuController::createButton(), 0, 'dialog', 'drawer', true);
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\AdminMenuController::createButton(), 1, 'xs', 'sm', 'md', 'lg', 'xl', 'full');
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\AdminMenuController::rowEditButton(), 0, 'dialog', 'drawer', true);
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\AdminMenuController::rowEditButton(), 1, 'xs', 'sm', 'md', 'lg', 'xl', 'full');
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\AdminMenuController::rowShowButton(), 0, 'dialog', 'drawer', true);
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\AdminMenuController::rowShowButton(), 1, 'xs', 'sm', 'md', 'lg', 'xl', 'full');
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\AdminMenuController::rowActions(), 0, 'dialog', 'drawer', true);
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\AdminMenuController::rowActions(), 1, 'xs', 'sm', 'md', 'lg', 'xl', 'full');
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\AdminRoleController::createButton(), 0, 'dialog', 'drawer', true);
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\AdminRoleController::createButton(), 1, 'xs', 'sm', 'md', 'lg', 'xl', 'full');
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\AdminRoleController::rowEditButton(), 0, 'dialog', 'drawer', true);
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\AdminRoleController::rowEditButton(), 1, 'xs', 'sm', 'md', 'lg', 'xl', 'full');
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\AdminRoleController::rowShowButton(), 0, 'dialog', 'drawer', true);
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\AdminRoleController::rowShowButton(), 1, 'xs', 'sm', 'md', 'lg', 'xl', 'full');
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\AdminRoleController::rowActions(), 0, 'dialog', 'drawer', true);
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\AdminRoleController::rowActions(), 1, 'xs', 'sm', 'md', 'lg', 'xl', 'full');
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\AdminPermissionController::createButton(), 0, 'dialog', 'drawer', true);
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\AdminPermissionController::createButton(), 1, 'xs', 'sm', 'md', 'lg', 'xl', 'full');
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\AdminPermissionController::rowEditButton(), 0, 'dialog', 'drawer', true);
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\AdminPermissionController::rowEditButton(), 1, 'xs', 'sm', 'md', 'lg', 'xl', 'full');
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\AdminPermissionController::rowShowButton(), 0, 'dialog', 'drawer', true);
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\AdminPermissionController::rowShowButton(), 1, 'xs', 'sm', 'md', 'lg', 'xl', 'full');
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\AdminPermissionController::rowActions(), 0, 'dialog', 'drawer', true);
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\AdminPermissionController::rowActions(), 1, 'xs', 'sm', 'md', 'lg', 'xl', 'full');
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\DevTools\CodeGeneratorController::createButton(), 0, 'dialog', 'drawer', true);
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\DevTools\CodeGeneratorController::createButton(), 1, 'xs', 'sm', 'md', 'lg', 'xl', 'full');
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\DevTools\CodeGeneratorController::rowEditButton(), 0, 'dialog', 'drawer', true);
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\DevTools\CodeGeneratorController::rowEditButton(), 1, 'xs', 'sm', 'md', 'lg', 'xl', 'full');
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\DevTools\CodeGeneratorController::rowShowButton(), 0, 'dialog', 'drawer', true);
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\DevTools\CodeGeneratorController::rowShowButton(), 1, 'xs', 'sm', 'md', 'lg', 'xl', 'full');
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\DevTools\CodeGeneratorController::rowActions(), 0, 'dialog', 'drawer', true);
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\DevTools\CodeGeneratorController::rowActions(), 1, 'xs', 'sm', 'md', 'lg', 'xl', 'full');
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\DevTools\PagesController::createButton(), 0, 'dialog', 'drawer', true);
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\DevTools\PagesController::createButton(), 1, 'xs', 'sm', 'md', 'lg', 'xl', 'full');
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\DevTools\PagesController::rowEditButton(), 0, 'dialog', 'drawer', true);
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\DevTools\PagesController::rowEditButton(), 1, 'xs', 'sm', 'md', 'lg', 'xl', 'full');
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\DevTools\PagesController::rowShowButton(), 0, 'dialog', 'drawer', true);
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\DevTools\PagesController::rowShowButton(), 1, 'xs', 'sm', 'md', 'lg', 'xl', 'full');
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\DevTools\PagesController::rowActions(), 0, 'dialog', 'drawer', true);
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\DevTools\PagesController::rowActions(), 1, 'xs', 'sm', 'md', 'lg', 'xl', 'full');
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\DevTools\RelationshipController::createButton(), 0, 'dialog', 'drawer', true);
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\DevTools\RelationshipController::createButton(), 1, 'xs', 'sm', 'md', 'lg', 'xl', 'full');
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\DevTools\RelationshipController::rowEditButton(), 0, 'dialog', 'drawer', true);
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\DevTools\RelationshipController::rowEditButton(), 1, 'xs', 'sm', 'md', 'lg', 'xl', 'full');
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\DevTools\RelationshipController::rowShowButton(), 0, 'dialog', 'drawer', true);
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\DevTools\RelationshipController::rowShowButton(), 1, 'xs', 'sm', 'md', 'lg', 'xl', 'full');
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\DevTools\RelationshipController::rowActions(), 0, 'dialog', 'drawer', true);
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\DevTools\RelationshipController::rowActions(), 1, 'xs', 'sm', 'md', 'lg', 'xl', 'full');
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\DevTools\ApiController::createButton(), 0, 'dialog', 'drawer', true);
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\DevTools\ApiController::createButton(), 1, 'xs', 'sm', 'md', 'lg', 'xl', 'full');
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\DevTools\ApiController::rowEditButton(), 0, 'dialog', 'drawer', true);
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\DevTools\ApiController::rowEditButton(), 1, 'xs', 'sm', 'md', 'lg', 'xl', 'full');
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\DevTools\ApiController::rowShowButton(), 0, 'dialog', 'drawer', true);
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\DevTools\ApiController::rowShowButton(), 1, 'xs', 'sm', 'md', 'lg', 'xl', 'full');
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\DevTools\ApiController::rowActions(), 0, 'dialog', 'drawer', true);
	expectedArguments(\Slowlyo\OwlAdmin\Controllers\DevTools\ApiController::rowActions(), 1, 'xs', 'sm', 'md', 'lg', 'xl', 'full');
	expectedArguments(\App\Admin\Controllers\UserController::createButton(), 0, 'dialog', 'drawer', true);
	expectedArguments(\App\Admin\Controllers\UserController::createButton(), 1, 'xs', 'sm', 'md', 'lg', 'xl', 'full');
	expectedArguments(\App\Admin\Controllers\UserController::rowEditButton(), 0, 'dialog', 'drawer', true);
	expectedArguments(\App\Admin\Controllers\UserController::rowEditButton(), 1, 'xs', 'sm', 'md', 'lg', 'xl', 'full');
	expectedArguments(\App\Admin\Controllers\UserController::rowShowButton(), 0, 'dialog', 'drawer', true);
	expectedArguments(\App\Admin\Controllers\UserController::rowShowButton(), 1, 'xs', 'sm', 'md', 'lg', 'xl', 'full');
	expectedArguments(\App\Admin\Controllers\UserController::rowActions(), 0, 'dialog', 'drawer', true);
	expectedArguments(\App\Admin\Controllers\UserController::rowActions(), 1, 'xs', 'sm', 'md', 'lg', 'xl', 'full');
	expectedArguments(\Slowlyo\OwlDict\Http\Controllers\OwlDictController::createButton(), 0, 'dialog', 'drawer', true);
	expectedArguments(\Slowlyo\OwlDict\Http\Controllers\OwlDictController::createButton(), 1, 'xs', 'sm', 'md', 'lg', 'xl', 'full');
	expectedArguments(\Slowlyo\OwlDict\Http\Controllers\OwlDictController::rowEditButton(), 0, 'dialog', 'drawer', true);
	expectedArguments(\Slowlyo\OwlDict\Http\Controllers\OwlDictController::rowEditButton(), 1, 'xs', 'sm', 'md', 'lg', 'xl', 'full');
	expectedArguments(\Slowlyo\OwlDict\Http\Controllers\OwlDictController::rowShowButton(), 0, 'dialog', 'drawer', true);
	expectedArguments(\Slowlyo\OwlDict\Http\Controllers\OwlDictController::rowShowButton(), 1, 'xs', 'sm', 'md', 'lg', 'xl', 'full');
	expectedArguments(\Slowlyo\OwlDict\Http\Controllers\OwlDictController::rowActions(), 0, 'dialog', 'drawer', true);
	expectedArguments(\Slowlyo\OwlDict\Http\Controllers\OwlDictController::rowActions(), 1, 'xs', 'sm', 'md', 'lg', 'xl', 'full');
}
