<?php

// =====================================================================

// !!  路由文件由 owl-admin 自动生成，请不要手动修改。

// !!  Route file auto generated by owl-admin, don't modify it manually.

// =====================================================================

use Slowlyo\OwlAdmin\Admin;
use Illuminate\Routing\Router;
use Illuminate\Support\Facades\Route;

Route::group([
    'domain'     => Admin::config('admin.route.domain'),
    'prefix'     => Admin::config('admin.route.prefix'),
    'middleware' => Admin::config('admin.route.middleware'),
], function (Router $router) {
    // 用户管理
    $router->resource('users', \App\Admin\Controllers\UserController::class);
    // 配置分类
    $router->resource('system_config_tab', \App\Admin\Controllers\SystemConfigTabController::class);
    // 配置项
    $router->resource('system_config', \App\Admin\Controllers\SystemConfigController::class);

});