<?php

// =====================================================================

// !!  路由文件由 owl-admin 自动生成，请不要手动修改。

// !!  Route file auto generated by owl-admin, don't modify it manually.

// =====================================================================

use Slowlyo\OwlAdmin\Admin;
use Illuminate\Routing\Router;
use Illuminate\Support\Facades\Route;

Route::group([
    'domain'     => Admin::config('admin.route.domain'),
    'prefix'     => Admin::config('admin.route.prefix'),
    'middleware' => Admin::config('admin.route.middleware'),
], function (Router $router) {
    // 用户管理
    $router->resource('users', \App\Admin\Controllers\UserController::class);
   $router->get('/banner_categories/bannerCategory', [\Zmc\Banner\Http\Controllers\BannerCategorieController::class, 'bannerCategory']);
    // 轮播图分类
    $router->resource('banner_categories', \Zmc\Banner\Http\Controllers\BannerCategorieController::class);
    // 轮播图设置
    $router->resource('banners', \Zmc\Banner\Http\Controllers\BannerController::class);

});
